name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test
      - name: auto release
        uses: ./
        with:
          plugins: |
            git-tag
            released
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
